"""证件照 / 职业形象照规格库。"""

BG_COLORS = {
    "blue": "#1a73e8",
    "white": "#ffffff",
    "red": "#e53935",
    "lightBlue": "#81d4fa",
    "gray": "#9e9e9e",
    "darkBlue": "#0b3d91",
}

PHOTO_SPECS = {
    "one-inch": {
        "id": "one-inch",
        "name": "一寸照",
        "category": "common",
        "width": 295,
        "height": 413,
        "widthMm": 25,
        "heightMm": 35,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "two-inch": {
        "id": "two-inch",
        "name": "二寸照",
        "category": "common",
        "width": 413,
        "height": 579,
        "widthMm": 35,
        "heightMm": 49,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "small-one-inch": {
        "id": "small-one-inch",
        "name": "小一寸",
        "category": "common",
        "width": 260,
        "height": 378,
        "widthMm": 22,
        "heightMm": 32,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "large-one-inch": {
        "id": "large-one-inch",
        "name": "大一寸",
        "category": "common",
        "width": 390,
        "height": 567,
        "widthMm": 33,
        "heightMm": 48,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "small-two-inch": {
        "id": "small-two-inch",
        "name": "小二寸",
        "category": "common",
        "width": 413,
        "height": 531,
        "widthMm": 35,
        "heightMm": 45,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "large-two-inch": {
        "id": "large-two-inch",
        "name": "大二寸",
        "category": "common",
        "width": 413,
        "height": 626,
        "widthMm": 35,
        "heightMm": 53,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "id-card-cn": {
        "id": "id-card-cn",
        "name": "二代身份证数码照",
        "category": "id_card",
        "width": 358,
        "height": 441,
        "dpi": 350,
        "defaultBg": "white",
        "format": "JPEG",
        "composition": "head_shoulder",
        "mode": "official",
        "note": "24位RGB，正面免冠，露双肩。",
    },
    "social-security-cn": {
        "id": "social-security-cn",
        "name": "社保卡数码照",
        "category": "social_security",
        "width": 358,
        "height": 441,
        "dpi": 350,
        "defaultBg": "white",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "passport-cn": {
        "id": "passport-cn",
        "name": "普通护照照片",
        "category": "passport",
        "width": 390,
        "height": 567,
        "widthMm": 33,
        "heightMm": 48,
        "defaultBg": "white",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "exit-entry-cn": {
        "id": "exit-entry-cn",
        "name": "港澳通行证/出入境证件",
        "category": "passport",
        "width": 390,
        "height": 567,
        "defaultBg": "lightBlue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "teacher-exam": {
        "id": "teacher-exam",
        "name": "教师资格证报名照",
        "category": "exam",
        "width": 295,
        "height": 413,
        "defaultBg": "white",
        "format": "JPG/JPEG",
        "maxKb": 200,
        "composition": "head_shoulder",
        "mode": "official",
    },
    "civil-service-exam": {
        "id": "civil-service-exam",
        "name": "公务员考试报名照",
        "category": "exam",
        "width": 413,
        "height": 531,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "postgraduate-exam": {
        "id": "postgraduate-exam",
        "name": "研究生考试报名照",
        "category": "exam",
        "width": 390,
        "height": 567,
        "defaultBg": "white",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "cet-exam": {
        "id": "cet-exam",
        "name": "英语四六级报名照",
        "category": "exam",
        "width": 390,
        "height": 567,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "computer-exam": {
        "id": "computer-exam",
        "name": "计算机等级考试报名照",
        "category": "exam",
        "width": 390,
        "height": 567,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "official",
    },
    "resume-headshot": {
        "id": "resume-headshot",
        "name": "简历头像",
        "category": "resume",
        "width": 295,
        "height": 413,
        "defaultBg": "gray",
        "composition": "head_shoulder",
        "mode": "creative",
    },
    "career-headshot": {
        "id": "career-headshot",
        "name": "职业形象照",
        "category": "career",
        "width": 413,
        "height": 579,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "creative",
    },
    "career-half-body": {
        "id": "career-half-body",
        "name": "半身职业照",
        "category": "career",
        "width": 413,
        "height": 579,
        "defaultBg": "blue",
        "composition": "half_body",
        "mode": "creative",
    },
    "anime-blue-headshot": {
        "id": "anime-blue-headshot",
        "name": "二次元蓝底头像照",
        "category": "anime",
        "width": 295,
        "height": 413,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "anime",
    },
    "anime-white-headshot": {
        "id": "anime-white-headshot",
        "name": "二次元白底头像照",
        "category": "anime",
        "width": 295,
        "height": 413,
        "defaultBg": "white",
        "composition": "head_shoulder",
        "mode": "anime",
    },
    "anime-red-headshot": {
        "id": "anime-red-headshot",
        "name": "二次元红底头像照",
        "category": "anime",
        "width": 295,
        "height": 413,
        "defaultBg": "red",
        "composition": "head_shoulder",
        "mode": "anime",
    },
    "anime-career": {
        "id": "anime-career",
        "name": "二次元职业形象照",
        "category": "anime",
        "width": 413,
        "height": 579,
        "defaultBg": "blue",
        "composition": "head_shoulder",
        "mode": "anime",
    },
    "creative-square-avatar": {
        "id": "creative-square-avatar",
        "name": "创意方形头像",
        "category": "creative",
        "width": 512,
        "height": 512,
        "defaultBg": "lightBlue",
        "composition": "square_avatar",
        "mode": "creative",
    },
}

DEFAULT_SPEC_BY_PURPOSE = {
    "official_id_photo": "one-inch",
    "id_card": "id-card-cn",
    "social_security": "social-security-cn",
    "passport": "passport-cn",
    "teacher_exam": "teacher-exam",
    "civil_service_exam": "civil-service-exam",
    "resume": "resume-headshot",
    "career_portrait": "career-headshot",
    "anime_avatar": "anime-blue-headshot",
    "creative_id_photo": "creative-square-avatar",
}


def get_spec(spec_id=None, purpose=None):
    spec = PHOTO_SPECS.get(spec_id or "")
    if spec is None:
        spec = PHOTO_SPECS[DEFAULT_SPEC_BY_PURPOSE.get(purpose or "", "one-inch")]
    return dict(spec)
